### ISSUE TITLE
Is a server a must!

### ISSUE THREAD

**Issue by hyousef** [bwu-dart/bwu_polymer_routing#1]
Does this need server to run, it worked perfectly once I run it from DART editor (Dev SDK), but once I opened the file in DARTIUM, only the last line appeared (the link for the git site)!

**Comment by zoechi** [comment]
Sorry I totally missed this issue. You need a server when you use pushState which uses virtual URIs. If you are comfortable with URL fragments `http://www.somedomain.com/myapp.html#someroute` then this works without a server.
