### ISSUE TITLE
Clicking on links changes the URL, but typing the URL goes to 404

### ISSUE THREAD

**Issue by PushkaCom** [bwu-dart/bwu_polymer_routing#7]
**//EDIT//**

Ok - I found that for testing it is run on a Node.js server,

// let pushState and the router do the navigation. return index.html for all non-static-content routes.
app.get('*', function(req, res) {
  res.sendFile(__dirname + '/index.html');
});

so all traffic goes through index.html and it serves the right files accordingly 

How would this work on an apache server? 
still using a JS file?
.htaccess rewriting?

**Original issue submission**

Hi , in the demo site, I can get to a page via link, but not through the URL - is this normal?

http://bwu-dart.github.io/users
click Peter
http://bwu-dart.github.io/user/Peter/articles

copy paste to new tab
http://bwu-dart.github.io/user/Peter/articles

404
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus

I find it the same with this App Router - 
Though their demo site works like a normal website without the above error - though when I download/ upload to my server - it is the same as above.. 
Anyone know how to get URLs working?
Need to link incoming URL requests to index.html or something?

https://github.com/erikringsmuth/polymer-router-demos

**Comment by PushkaCom** [comment]
Ahg, I found something - a .htaccess solution 

<ifModule mod_rewrite.c>
  Options +FollowSymLinks
  IndexIgnore */*
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule (.*) index.html
</ifModule>

found it here:

https://gist.github.com/rayfranco/3211654

**Comment by zoechi** [comment]
Yup, if you use usePushState you need server support.
